# Generated by Django 5.0.2 on 2024-02-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('rate', models.FloatField()),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('actors', models.TextField()),
                ('genres', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
